'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System.Xml.Serialization

'
'This source code was auto-generated by xsd, Version=4.6.1055.0.
'

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true),  _
 System.Xml.Serialization.XmlRootAttribute([Namespace]:="", IsNullable:=false)>  _
Partial Public Class StatusResult
    
    Private statusField As String
    
    Private currentScreenField As String
    
    Private responseMessageField As String
    
    Private serialNumberField As String
    
    Private applicationVersionField As String
    
    Private oSVersionField As String
    
    Private additionalParametersField As AdditionalParameters
    
    Private removeEMVCardField As Boolean
    
    Private removeEMVCardFieldSpecified As Boolean
    
    '''<remarks/>
    Public Property Status() As String
        Get
            Return Me.statusField
        End Get
        Set
            Me.statusField = value
        End Set
    End Property
    
    '''<remarks/>
    Public Property CurrentScreen() As String
        Get
            Return Me.currentScreenField
        End Get
        Set
            Me.currentScreenField = value
        End Set
    End Property
    
    '''<remarks/>
    Public Property ResponseMessage() As String
        Get
            Return Me.responseMessageField
        End Get
        Set
            Me.responseMessageField = value
        End Set
    End Property
    
    '''<remarks/>
    Public Property SerialNumber() As String
        Get
            Return Me.serialNumberField
        End Get
        Set
            Me.serialNumberField = value
        End Set
    End Property
    
    '''<remarks/>
    Public Property ApplicationVersion() As String
        Get
            Return Me.applicationVersionField
        End Get
        Set
            Me.applicationVersionField = value
        End Set
    End Property
    
    '''<remarks/>
    Public Property OSVersion() As String
        Get
            Return Me.oSVersionField
        End Get
        Set
            Me.oSVersionField = value
        End Set
    End Property
    
    '''<remarks/>
    Public Property AdditionalParameters() As AdditionalParameters
        Get
            Return Me.additionalParametersField
        End Get
        Set
            Me.additionalParametersField = value
        End Set
    End Property
    
    '''<remarks/>
    Public Property RemoveEMVCard() As Boolean
        Get
            Return Me.removeEMVCardField
        End Get
        Set
            Me.removeEMVCardField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlIgnoreAttribute()>  _
    Public Property RemoveEMVCardSpecified() As Boolean
        Get
            Return Me.removeEMVCardFieldSpecified
        End Get
        Set
            Me.removeEMVCardFieldSpecified = value
        End Set
    End Property
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code")>  _
Partial Public Class AdditionalParameters
    
    Private paymentDataCapturedField As Boolean
    
    Private paymentDataCapturedFieldSpecified As Boolean
    
    Private removeEMVCardField As Boolean
    
    Private removeEMVCardFieldSpecified As Boolean
    
    Private signatureDataField As String
    
    Private amountDetailsField As AdditionalParametersAmountDetails
    
    Private ebtDetailsField As AdditionalParametersEbtDetails
    
    Private trackingIdField As String
    
    Private eMVField As AdditionalParametersEMV
    
    Private keyedDetailsField As AdditionalParametersKeyedDetails
    
    Private multiTenderField As AdditionalParametersMultiTender
    
    Private loyaltyField As AdditionalParametersLoyalty
    
    '''<remarks/>
    Public Property PaymentDataCaptured() As Boolean
        Get
            Return Me.paymentDataCapturedField
        End Get
        Set
            Me.paymentDataCapturedField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlIgnoreAttribute()>  _
    Public Property PaymentDataCapturedSpecified() As Boolean
        Get
            Return Me.paymentDataCapturedFieldSpecified
        End Get
        Set
            Me.paymentDataCapturedFieldSpecified = value
        End Set
    End Property
    
    '''<remarks/>
    Public Property RemoveEMVCard() As Boolean
        Get
            Return Me.removeEMVCardField
        End Get
        Set
            Me.removeEMVCardField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlIgnoreAttribute()>  _
    Public Property RemoveEMVCardSpecified() As Boolean
        Get
            Return Me.removeEMVCardFieldSpecified
        End Get
        Set
            Me.removeEMVCardFieldSpecified = value
        End Set
    End Property
    
    '''<remarks/>
    Public Property SignatureData() As String
        Get
            Return Me.signatureDataField
        End Get
        Set
            Me.signatureDataField = value
        End Set
    End Property
    
    '''<remarks/>
    Public Property AmountDetails() As AdditionalParametersAmountDetails
        Get
            Return Me.amountDetailsField
        End Get
        Set
            Me.amountDetailsField = value
        End Set
    End Property
    
    '''<remarks/>
    Public Property EbtDetails() As AdditionalParametersEbtDetails
        Get
            Return Me.ebtDetailsField
        End Get
        Set
            Me.ebtDetailsField = value
        End Set
    End Property
    
    '''<remarks/>
    Public Property TrackingId() As String
        Get
            Return Me.trackingIdField
        End Get
        Set
            Me.trackingIdField = value
        End Set
    End Property
    
    '''<remarks/>
    Public Property EMV() As AdditionalParametersEMV
        Get
            Return Me.eMVField
        End Get
        Set
            Me.eMVField = value
        End Set
    End Property
    
    '''<remarks/>
    Public Property KeyedDetails() As AdditionalParametersKeyedDetails
        Get
            Return Me.keyedDetailsField
        End Get
        Set
            Me.keyedDetailsField = value
        End Set
    End Property
    
    '''<remarks/>
    Public Property MultiTender() As AdditionalParametersMultiTender
        Get
            Return Me.multiTenderField
        End Get
        Set
            Me.multiTenderField = value
        End Set
    End Property
    
    '''<remarks/>
    Public Property Loyalty() As AdditionalParametersLoyalty
        Get
            Return Me.loyaltyField
        End Get
        Set
            Me.loyaltyField = value
        End Set
    End Property
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true)>  _
Partial Public Class AdditionalParametersAmountDetails
    
    Private userTipField As Decimal
    
    Private cashbackField As Decimal
    
    Private donationField As Decimal
    
    Private surchargeField As Decimal
    
    Private remainingCardBalanceField As String
    
    Private discountField() As AdditionalParametersAmountDetailsDiscount
    
    '''<remarks/>
    Public Property UserTip() As Decimal
        Get
            Return Me.userTipField
        End Get
        Set
            Me.userTipField = value
        End Set
    End Property
    
    '''<remarks/>
    Public Property Cashback() As Decimal
        Get
            Return Me.cashbackField
        End Get
        Set
            Me.cashbackField = value
        End Set
    End Property
    
    '''<remarks/>
    Public Property Donation() As Decimal
        Get
            Return Me.donationField
        End Get
        Set
            Me.donationField = value
        End Set
    End Property
    
    '''<remarks/>
    Public Property Surcharge() As Decimal
        Get
            Return Me.surchargeField
        End Get
        Set
            Me.surchargeField = value
        End Set
    End Property
    
    '''<remarks/>
    Public Property RemainingCardBalance() As String
        Get
            Return Me.remainingCardBalanceField
        End Get
        Set
            Me.remainingCardBalanceField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute("Discount")>  _
    Public Property Discount() As AdditionalParametersAmountDetailsDiscount()
        Get
            Return Me.discountField
        End Get
        Set
            Me.discountField = value
        End Set
    End Property
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true)>  _
Partial Public Class AdditionalParametersAmountDetailsDiscount
    
    Private totalField As Decimal
    
    '''<remarks/>
    Public Property Total() As Decimal
        Get
            Return Me.totalField
        End Get
        Set
            Me.totalField = value
        End Set
    End Property
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true)>  _
Partial Public Class AdditionalParametersEbtDetails
    
    Private ebtTypeField As String
    
    Private balancesField As AdditionalParametersEbtDetailsBalances
    
    '''<remarks/>
    Public Property EbtType() As String
        Get
            Return Me.ebtTypeField
        End Get
        Set
            Me.ebtTypeField = value
        End Set
    End Property
    
    '''<remarks/>
    Public Property Balances() As AdditionalParametersEbtDetailsBalances
        Get
            Return Me.balancesField
        End Get
        Set
            Me.balancesField = value
        End Set
    End Property
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true)>  _
Partial Public Class AdditionalParametersEbtDetailsBalances
    
    Private cashAvailableBalanceField As Decimal
    
    Private snapAvailableBalanceField As Decimal
    
    '''<remarks/>
    Public Property CashAvailableBalance() As Decimal
        Get
            Return Me.cashAvailableBalanceField
        End Get
        Set
            Me.cashAvailableBalanceField = value
        End Set
    End Property
    
    '''<remarks/>
    Public Property SnapAvailableBalance() As Decimal
        Get
            Return Me.snapAvailableBalanceField
        End Get
        Set
            Me.snapAvailableBalanceField = value
        End Set
    End Property
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true)>  _
Partial Public Class AdditionalParametersEMV
    
    Private applicationInformationField As AdditionalParametersEMVApplicationInformation
    
    Private cardInformationField As AdditionalParametersEMVCardInformation
    
    Private applicationCryptogramField As AdditionalParametersEMVApplicationCryptogram
    
    Private cvmResultsField As String
    
    Private issuerApplicationDataField As String
    
    Private terminalVerificationResultsField As String
    
    Private unpredictableNumberField As String
    
    Private amountField As AdditionalParametersEMVAmount
    
    Private posEntryModeField As String
    
    Private terminalInformationField As AdditionalParametersEMVTerminalInformation
    
    Private transactionInformationField As AdditionalParametersEMVTransactionInformation
    
    Private cryptogramInformationDataField As String
    
    Private pINStatementField As String
    
    Private cvmMethodField As String
    
    Private issuerActionCodeDefaultField As String
    
    Private issuerActionCodeDenialField As String
    
    Private issuerActionCodeOnlineField As String
    
    Private authorizationResponseCodeField As String
    
    '''<remarks/>
    Public Property ApplicationInformation() As AdditionalParametersEMVApplicationInformation
        Get
            Return Me.applicationInformationField
        End Get
        Set
            Me.applicationInformationField = value
        End Set
    End Property
    
    '''<remarks/>
    Public Property CardInformation() As AdditionalParametersEMVCardInformation
        Get
            Return Me.cardInformationField
        End Get
        Set
            Me.cardInformationField = value
        End Set
    End Property
    
    '''<remarks/>
    Public Property ApplicationCryptogram() As AdditionalParametersEMVApplicationCryptogram
        Get
            Return Me.applicationCryptogramField
        End Get
        Set
            Me.applicationCryptogramField = value
        End Set
    End Property
    
    '''<remarks/>
    Public Property CvmResults() As String
        Get
            Return Me.cvmResultsField
        End Get
        Set
            Me.cvmResultsField = value
        End Set
    End Property
    
    '''<remarks/>
    Public Property IssuerApplicationData() As String
        Get
            Return Me.issuerApplicationDataField
        End Get
        Set
            Me.issuerApplicationDataField = value
        End Set
    End Property
    
    '''<remarks/>
    Public Property TerminalVerificationResults() As String
        Get
            Return Me.terminalVerificationResultsField
        End Get
        Set
            Me.terminalVerificationResultsField = value
        End Set
    End Property
    
    '''<remarks/>
    Public Property UnpredictableNumber() As String
        Get
            Return Me.unpredictableNumberField
        End Get
        Set
            Me.unpredictableNumberField = value
        End Set
    End Property
    
    '''<remarks/>
    Public Property Amount() As AdditionalParametersEMVAmount
        Get
            Return Me.amountField
        End Get
        Set
            Me.amountField = value
        End Set
    End Property
    
    '''<remarks/>
    Public Property PosEntryMode() As String
        Get
            Return Me.posEntryModeField
        End Get
        Set
            Me.posEntryModeField = value
        End Set
    End Property
    
    '''<remarks/>
    Public Property TerminalInformation() As AdditionalParametersEMVTerminalInformation
        Get
            Return Me.terminalInformationField
        End Get
        Set
            Me.terminalInformationField = value
        End Set
    End Property
    
    '''<remarks/>
    Public Property TransactionInformation() As AdditionalParametersEMVTransactionInformation
        Get
            Return Me.transactionInformationField
        End Get
        Set
            Me.transactionInformationField = value
        End Set
    End Property
    
    '''<remarks/>
    Public Property CryptogramInformationData() As String
        Get
            Return Me.cryptogramInformationDataField
        End Get
        Set
            Me.cryptogramInformationDataField = value
        End Set
    End Property
    
    '''<remarks/>
    Public Property PINStatement() As String
        Get
            Return Me.pINStatementField
        End Get
        Set
            Me.pINStatementField = value
        End Set
    End Property
    
    '''<remarks/>
    Public Property CvmMethod() As String
        Get
            Return Me.cvmMethodField
        End Get
        Set
            Me.cvmMethodField = value
        End Set
    End Property
    
    '''<remarks/>
    Public Property IssuerActionCodeDefault() As String
        Get
            Return Me.issuerActionCodeDefaultField
        End Get
        Set
            Me.issuerActionCodeDefaultField = value
        End Set
    End Property
    
    '''<remarks/>
    Public Property IssuerActionCodeDenial() As String
        Get
            Return Me.issuerActionCodeDenialField
        End Get
        Set
            Me.issuerActionCodeDenialField = value
        End Set
    End Property
    
    '''<remarks/>
    Public Property IssuerActionCodeOnline() As String
        Get
            Return Me.issuerActionCodeOnlineField
        End Get
        Set
            Me.issuerActionCodeOnlineField = value
        End Set
    End Property
    
    '''<remarks/>
    Public Property AuthorizationResponseCode() As String
        Get
            Return Me.authorizationResponseCodeField
        End Get
        Set
            Me.authorizationResponseCodeField = value
        End Set
    End Property
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true)>  _
Partial Public Class AdditionalParametersEMVApplicationInformation
    
    Private aidField As String
    
    Private applicationLabelField As String
    
    Private applicationExpiryDateField As String
    
    Private applicationEffectiveDateField As String
    
    Private applicationInterchangeProfileField As String
    
    Private applicationVersionNumberField As String
    
    Private applicationTransactionCounterField As String
    
    Private applicationUsageControlField As String
    
    Private applicationPreferredNameField As String
    
    Private applicationDisplayNameField As String
    
    '''<remarks/>
    Public Property Aid() As String
        Get
            Return Me.aidField
        End Get
        Set
            Me.aidField = value
        End Set
    End Property
    
    '''<remarks/>
    Public Property ApplicationLabel() As String
        Get
            Return Me.applicationLabelField
        End Get
        Set
            Me.applicationLabelField = value
        End Set
    End Property
    
    '''<remarks/>
    Public Property ApplicationExpiryDate() As String
        Get
            Return Me.applicationExpiryDateField
        End Get
        Set
            Me.applicationExpiryDateField = value
        End Set
    End Property
    
    '''<remarks/>
    Public Property ApplicationEffectiveDate() As String
        Get
            Return Me.applicationEffectiveDateField
        End Get
        Set
            Me.applicationEffectiveDateField = value
        End Set
    End Property
    
    '''<remarks/>
    Public Property ApplicationInterchangeProfile() As String
        Get
            Return Me.applicationInterchangeProfileField
        End Get
        Set
            Me.applicationInterchangeProfileField = value
        End Set
    End Property
    
    '''<remarks/>
    Public Property ApplicationVersionNumber() As String
        Get
            Return Me.applicationVersionNumberField
        End Get
        Set
            Me.applicationVersionNumberField = value
        End Set
    End Property
    
    '''<remarks/>
    Public Property ApplicationTransactionCounter() As String
        Get
            Return Me.applicationTransactionCounterField
        End Get
        Set
            Me.applicationTransactionCounterField = value
        End Set
    End Property
    
    '''<remarks/>
    Public Property ApplicationUsageControl() As String
        Get
            Return Me.applicationUsageControlField
        End Get
        Set
            Me.applicationUsageControlField = value
        End Set
    End Property
    
    '''<remarks/>
    Public Property ApplicationPreferredName() As String
        Get
            Return Me.applicationPreferredNameField
        End Get
        Set
            Me.applicationPreferredNameField = value
        End Set
    End Property
    
    '''<remarks/>
    Public Property ApplicationDisplayName() As String
        Get
            Return Me.applicationDisplayNameField
        End Get
        Set
            Me.applicationDisplayNameField = value
        End Set
    End Property
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true)>  _
Partial Public Class AdditionalParametersEMVCardInformation
    
    Private maskedPanField As String
    
    Private panSequenceNumberField As String
    
    Private cardExpiryDateField As String
    
    '''<remarks/>
    Public Property MaskedPan() As String
        Get
            Return Me.maskedPanField
        End Get
        Set
            Me.maskedPanField = value
        End Set
    End Property
    
    '''<remarks/>
    Public Property PanSequenceNumber() As String
        Get
            Return Me.panSequenceNumberField
        End Get
        Set
            Me.panSequenceNumberField = value
        End Set
    End Property
    
    '''<remarks/>
    Public Property CardExpiryDate() As String
        Get
            Return Me.cardExpiryDateField
        End Get
        Set
            Me.cardExpiryDateField = value
        End Set
    End Property
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true)>  _
Partial Public Class AdditionalParametersEMVApplicationCryptogram
    
    Private cryptogramTypeField As String
    
    Private cryptogramField As String
    
    '''<remarks/>
    Public Property CryptogramType() As String
        Get
            Return Me.cryptogramTypeField
        End Get
        Set
            Me.cryptogramTypeField = value
        End Set
    End Property
    
    '''<remarks/>
    Public Property Cryptogram() As String
        Get
            Return Me.cryptogramField
        End Get
        Set
            Me.cryptogramField = value
        End Set
    End Property
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true)>  _
Partial Public Class AdditionalParametersEMVAmount
    
    Private amountAuthorizedField As Decimal
    
    Private amountOtherField As Decimal
    
    '''<remarks/>
    Public Property AmountAuthorized() As Decimal
        Get
            Return Me.amountAuthorizedField
        End Get
        Set
            Me.amountAuthorizedField = value
        End Set
    End Property
    
    '''<remarks/>
    Public Property AmountOther() As Decimal
        Get
            Return Me.amountOtherField
        End Get
        Set
            Me.amountOtherField = value
        End Set
    End Property
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true)>  _
Partial Public Class AdditionalParametersEMVTerminalInformation
    
    Private terminalTypeField As String
    
    Private ifdSerialNumberField As String
    
    Private terminalCountryCodeField As String
    
    Private terminalIDField As String
    
    Private terminalActionCodeDefaultField As String
    
    Private terminalActionCodeDenialField As String
    
    Private terminalActionCodeOnlineField As String
    
    '''<remarks/>
    Public Property TerminalType() As String
        Get
            Return Me.terminalTypeField
        End Get
        Set
            Me.terminalTypeField = value
        End Set
    End Property
    
    '''<remarks/>
    Public Property IfdSerialNumber() As String
        Get
            Return Me.ifdSerialNumberField
        End Get
        Set
            Me.ifdSerialNumberField = value
        End Set
    End Property
    
    '''<remarks/>
    Public Property TerminalCountryCode() As String
        Get
            Return Me.terminalCountryCodeField
        End Get
        Set
            Me.terminalCountryCodeField = value
        End Set
    End Property
    
    '''<remarks/>
    Public Property TerminalID() As String
        Get
            Return Me.terminalIDField
        End Get
        Set
            Me.terminalIDField = value
        End Set
    End Property
    
    '''<remarks/>
    Public Property TerminalActionCodeDefault() As String
        Get
            Return Me.terminalActionCodeDefaultField
        End Get
        Set
            Me.terminalActionCodeDefaultField = value
        End Set
    End Property
    
    '''<remarks/>
    Public Property TerminalActionCodeDenial() As String
        Get
            Return Me.terminalActionCodeDenialField
        End Get
        Set
            Me.terminalActionCodeDenialField = value
        End Set
    End Property
    
    '''<remarks/>
    Public Property TerminalActionCodeOnline() As String
        Get
            Return Me.terminalActionCodeOnlineField
        End Get
        Set
            Me.terminalActionCodeOnlineField = value
        End Set
    End Property
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true)>  _
Partial Public Class AdditionalParametersEMVTransactionInformation
    
    Private transactionTypeField As String
    
    Private transactionCurrencyCodeField As String
    
    Private transactionStatusInformationField As String
    
    '''<remarks/>
    Public Property TransactionType() As String
        Get
            Return Me.transactionTypeField
        End Get
        Set
            Me.transactionTypeField = value
        End Set
    End Property
    
    '''<remarks/>
    Public Property TransactionCurrencyCode() As String
        Get
            Return Me.transactionCurrencyCodeField
        End Get
        Set
            Me.transactionCurrencyCodeField = value
        End Set
    End Property
    
    '''<remarks/>
    Public Property TransactionStatusInformation() As String
        Get
            Return Me.transactionStatusInformationField
        End Get
        Set
            Me.transactionStatusInformationField = value
        End Set
    End Property
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true)>  _
Partial Public Class AdditionalParametersKeyedDetails
    
    Private expirationDateField As String
    
    Private avsStreetZipCodeField As String
    
    Private avsResponseField As String
    
    Private cvResponseField As String
    
    '''<remarks/>
    Public Property ExpirationDate() As String
        Get
            Return Me.expirationDateField
        End Get
        Set
            Me.expirationDateField = value
        End Set
    End Property
    
    '''<remarks/>
    Public Property AvsStreetZipCode() As String
        Get
            Return Me.avsStreetZipCodeField
        End Get
        Set
            Me.avsStreetZipCodeField = value
        End Set
    End Property
    
    '''<remarks/>
    Public Property AvsResponse() As String
        Get
            Return Me.avsResponseField
        End Get
        Set
            Me.avsResponseField = value
        End Set
    End Property
    
    '''<remarks/>
    Public Property CvResponse() As String
        Get
            Return Me.cvResponseField
        End Get
        Set
            Me.cvResponseField = value
        End Set
    End Property
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true)>  _
Partial Public Class AdditionalParametersMultiTender
    
    Private transactionsField() As AdditionalParametersMultiTenderTransaction
    
    '''<remarks/>
    <System.Xml.Serialization.XmlArrayItemAttribute("Transaction", IsNullable:=false)>  _
    Public Property Transactions() As AdditionalParametersMultiTenderTransaction()
        Get
            Return Me.transactionsField
        End Get
        Set
            Me.transactionsField = value
        End Set
    End Property
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true)>  _
Partial Public Class AdditionalParametersMultiTenderTransaction
    
    Private statusField As String
    
    Private errorMessageField As String
    
    Private amountRequestedField As Decimal
    
    Private amountApprovedField As Decimal
    
    Private accountNumberField As String
    
    Private tokenField As String
    
    Private transactionTypeField As String
    
    Private paymentTypeField As String
    
    Private rewardField As AdditionalParametersMultiTenderTransactionReward
    
    '''<remarks/>
    Public Property Status() As String
        Get
            Return Me.statusField
        End Get
        Set
            Me.statusField = value
        End Set
    End Property
    
    '''<remarks/>
    Public Property ErrorMessage() As String
        Get
            Return Me.errorMessageField
        End Get
        Set
            Me.errorMessageField = value
        End Set
    End Property
    
    '''<remarks/>
    Public Property AmountRequested() As Decimal
        Get
            Return Me.amountRequestedField
        End Get
        Set
            Me.amountRequestedField = value
        End Set
    End Property
    
    '''<remarks/>
    Public Property AmountApproved() As Decimal
        Get
            Return Me.amountApprovedField
        End Get
        Set
            Me.amountApprovedField = value
        End Set
    End Property
    
    '''<remarks/>
    Public Property AccountNumber() As String
        Get
            Return Me.accountNumberField
        End Get
        Set
            Me.accountNumberField = value
        End Set
    End Property
    
    '''<remarks/>
    Public Property Token() As String
        Get
            Return Me.tokenField
        End Get
        Set
            Me.tokenField = value
        End Set
    End Property
    
    '''<remarks/>
    Public Property TransactionType() As String
        Get
            Return Me.transactionTypeField
        End Get
        Set
            Me.transactionTypeField = value
        End Set
    End Property
    
    '''<remarks/>
    Public Property PaymentType() As String
        Get
            Return Me.paymentTypeField
        End Get
        Set
            Me.paymentTypeField = value
        End Set
    End Property
    
    '''<remarks/>
    Public Property Reward() As AdditionalParametersMultiTenderTransactionReward
        Get
            Return Me.rewardField
        End Get
        Set
            Me.rewardField = value
        End Set
    End Property
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true)>  _
Partial Public Class AdditionalParametersMultiTenderTransactionReward
    
    Private errorMessageField As String
    
    Private accountNumberField As String
    
    Private typeField As String
    
    Private quantityField As String
    
    Private tokenField As String
    
    '''<remarks/>
    Public Property ErrorMessage() As String
        Get
            Return Me.errorMessageField
        End Get
        Set
            Me.errorMessageField = value
        End Set
    End Property
    
    '''<remarks/>
    Public Property AccountNumber() As String
        Get
            Return Me.accountNumberField
        End Get
        Set
            Me.accountNumberField = value
        End Set
    End Property
    
    '''<remarks/>
    Public Property Type() As String
        Get
            Return Me.typeField
        End Get
        Set
            Me.typeField = value
        End Set
    End Property
    
    '''<remarks/>
    Public Property Quantity() As String
        Get
            Return Me.quantityField
        End Get
        Set
            Me.quantityField = value
        End Set
    End Property
    
    '''<remarks/>
    Public Property Token() As String
        Get
            Return Me.tokenField
        End Get
        Set
            Me.tokenField = value
        End Set
    End Property
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true)>  _
Partial Public Class AdditionalParametersLoyalty
    
    Private accountNumberField As String
    
    Private balancesField As AdditionalParametersLoyaltyBalances
    
    Private pointsEarnedField As String
    
    '''<remarks/>
    Public Property AccountNumber() As String
        Get
            Return Me.accountNumberField
        End Get
        Set
            Me.accountNumberField = value
        End Set
    End Property
    
    '''<remarks/>
    Public Property Balances() As AdditionalParametersLoyaltyBalances
        Get
            Return Me.balancesField
        End Get
        Set
            Me.balancesField = value
        End Set
    End Property
    
    '''<remarks/>
    Public Property PointsEarned() As String
        Get
            Return Me.pointsEarnedField
        End Get
        Set
            Me.pointsEarnedField = value
        End Set
    End Property
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true)>  _
Partial Public Class AdditionalParametersLoyaltyBalances
    
    Private pointsBalanceField As String
    
    Private amountBalanceField As String
    
    '''<remarks/>
    Public Property PointsBalance() As String
        Get
            Return Me.pointsBalanceField
        End Get
        Set
            Me.pointsBalanceField = value
        End Set
    End Property
    
    '''<remarks/>
    Public Property AmountBalance() As String
        Get
            Return Me.amountBalanceField
        End Get
        Set
            Me.amountBalanceField = value
        End Set
    End Property
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true),  _
 System.Xml.Serialization.XmlRootAttribute([Namespace]:="", IsNullable:=false)>  _
Partial Public Class CancelResult
    
    Private statusField As String
    
    Private responseMessageField As String
    
    Private additionalParametersField As String
    
    '''<remarks/>
    Public Property Status() As String
        Get
            Return Me.statusField
        End Get
        Set
            Me.statusField = value
        End Set
    End Property
    
    '''<remarks/>
    Public Property ResponseMessage() As String
        Get
            Return Me.responseMessageField
        End Get
        Set
            Me.responseMessageField = value
        End Set
    End Property
    
    '''<remarks/>
    Public Property AdditionalParameters() As String
        Get
            Return Me.additionalParametersField
        End Get
        Set
            Me.additionalParametersField = value
        End Set
    End Property
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true),  _
 System.Xml.Serialization.XmlRootAttribute([Namespace]:="", IsNullable:=false)>  _
Partial Public Class OrderResult
    
    Private statusField As String
    
    Private responseMessageField As String
    
    Private itemsField As Decimal
    
    Private itemsFieldSpecified As Boolean
    
    Private discountsField As Decimal
    
    Private discountsFieldSpecified As Boolean
    
    Private totalAmountField As Decimal
    
    Private totalAmountFieldSpecified As Boolean
    
    Private customSubTotalField As String
    
    Private taxAmountField As Decimal
    
    Private taxAmountFieldSpecified As Boolean
    
    Private itemIDField As String
    
    Private additionalParametersField As AdditionalParameters
    
    '''<remarks/>
    Public Property Status() As String
        Get
            Return Me.statusField
        End Get
        Set
            Me.statusField = value
        End Set
    End Property
    
    '''<remarks/>
    Public Property ResponseMessage() As String
        Get
            Return Me.responseMessageField
        End Get
        Set
            Me.responseMessageField = value
        End Set
    End Property
    
    '''<remarks/>
    Public Property Items() As Decimal
        Get
            Return Me.itemsField
        End Get
        Set
            Me.itemsField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlIgnoreAttribute()>  _
    Public Property ItemsSpecified() As Boolean
        Get
            Return Me.itemsFieldSpecified
        End Get
        Set
            Me.itemsFieldSpecified = value
        End Set
    End Property
    
    '''<remarks/>
    Public Property Discounts() As Decimal
        Get
            Return Me.discountsField
        End Get
        Set
            Me.discountsField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlIgnoreAttribute()>  _
    Public Property DiscountsSpecified() As Boolean
        Get
            Return Me.discountsFieldSpecified
        End Get
        Set
            Me.discountsFieldSpecified = value
        End Set
    End Property
    
    '''<remarks/>
    Public Property TotalAmount() As Decimal
        Get
            Return Me.totalAmountField
        End Get
        Set
            Me.totalAmountField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlIgnoreAttribute()>  _
    Public Property TotalAmountSpecified() As Boolean
        Get
            Return Me.totalAmountFieldSpecified
        End Get
        Set
            Me.totalAmountFieldSpecified = value
        End Set
    End Property
    
    '''<remarks/>
    Public Property CustomSubTotal() As String
        Get
            Return Me.customSubTotalField
        End Get
        Set
            Me.customSubTotalField = value
        End Set
    End Property
    
    '''<remarks/>
    Public Property TaxAmount() As Decimal
        Get
            Return Me.taxAmountField
        End Get
        Set
            Me.taxAmountField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlIgnoreAttribute()>  _
    Public Property TaxAmountSpecified() As Boolean
        Get
            Return Me.taxAmountFieldSpecified
        End Get
        Set
            Me.taxAmountFieldSpecified = value
        End Set
    End Property
    
    '''<remarks/>
    Public Property ItemID() As String
        Get
            Return Me.itemIDField
        End Get
        Set
            Me.itemIDField = value
        End Set
    End Property
    
    '''<remarks/>
    Public Property AdditionalParameters() As AdditionalParameters
        Get
            Return Me.additionalParametersField
        End Get
        Set
            Me.additionalParametersField = value
        End Set
    End Property
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true),  _
 System.Xml.Serialization.XmlRootAttribute([Namespace]:="", IsNullable:=false)>  _
Partial Public Class OrderSnapshot
    
    Private statusField As String
    
    Private responseMessageField As String
    
    Private orderNumberField As String
    
    Private numberOfItemsField As String
    
    Private orderTaxField As Decimal
    
    Private orderTaxFieldSpecified As Boolean
    
    Private orderTotalField As Decimal
    
    Private orderTotalFieldSpecified As Boolean
    
    Private itemsField() As OrderSnapshotItem
    
    '''<remarks/>
    Public Property Status() As String
        Get
            Return Me.statusField
        End Get
        Set
            Me.statusField = value
        End Set
    End Property
    
    '''<remarks/>
    Public Property ResponseMessage() As String
        Get
            Return Me.responseMessageField
        End Get
        Set
            Me.responseMessageField = value
        End Set
    End Property
    
    '''<remarks/>
    Public Property OrderNumber() As String
        Get
            Return Me.orderNumberField
        End Get
        Set
            Me.orderNumberField = value
        End Set
    End Property
    
    '''<remarks/>
    Public Property NumberOfItems() As String
        Get
            Return Me.numberOfItemsField
        End Get
        Set
            Me.numberOfItemsField = value
        End Set
    End Property
    
    '''<remarks/>
    Public Property OrderTax() As Decimal
        Get
            Return Me.orderTaxField
        End Get
        Set
            Me.orderTaxField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlIgnoreAttribute()>  _
    Public Property OrderTaxSpecified() As Boolean
        Get
            Return Me.orderTaxFieldSpecified
        End Get
        Set
            Me.orderTaxFieldSpecified = value
        End Set
    End Property
    
    '''<remarks/>
    Public Property OrderTotal() As Decimal
        Get
            Return Me.orderTotalField
        End Get
        Set
            Me.orderTotalField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlIgnoreAttribute()>  _
    Public Property OrderTotalSpecified() As Boolean
        Get
            Return Me.orderTotalFieldSpecified
        End Get
        Set
            Me.orderTotalFieldSpecified = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlArrayItemAttribute("Item", IsNullable:=false)>  _
    Public Property Items() As OrderSnapshotItem()
        Get
            Return Me.itemsField
        End Get
        Set
            Me.itemsField = value
        End Set
    End Property
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true)>  _
Partial Public Class OrderSnapshotItem
    
    Private itemRequestTypeField As String
    
    Private itemIDField As String
    
    Private itemQuantityField As String
    
    Private itemAmountField As Decimal
    
    Private itemTotalAmountField As Decimal
    
    Private itemTaxAmountField As Decimal
    
    Private itemTaxTotalField As Decimal
    
    Private itemTypeField As String
    
    Private itemTypeValueField As String
    
    Private itemUPCField As String
    
    Private itemDescriptionField As String
    
    Private itemCategoryField As String
    
    '''<remarks/>
    Public Property ItemRequestType() As String
        Get
            Return Me.itemRequestTypeField
        End Get
        Set
            Me.itemRequestTypeField = value
        End Set
    End Property
    
    '''<remarks/>
    Public Property itemID() As String
        Get
            Return Me.itemIDField
        End Get
        Set
            Me.itemIDField = value
        End Set
    End Property
    
    '''<remarks/>
    Public Property itemQuantity() As String
        Get
            Return Me.itemQuantityField
        End Get
        Set
            Me.itemQuantityField = value
        End Set
    End Property
    
    '''<remarks/>
    Public Property itemAmount() As Decimal
        Get
            Return Me.itemAmountField
        End Get
        Set
            Me.itemAmountField = value
        End Set
    End Property
    
    '''<remarks/>
    Public Property itemTotalAmount() As Decimal
        Get
            Return Me.itemTotalAmountField
        End Get
        Set
            Me.itemTotalAmountField = value
        End Set
    End Property
    
    '''<remarks/>
    Public Property itemTaxAmount() As Decimal
        Get
            Return Me.itemTaxAmountField
        End Get
        Set
            Me.itemTaxAmountField = value
        End Set
    End Property
    
    '''<remarks/>
    Public Property itemTaxTotal() As Decimal
        Get
            Return Me.itemTaxTotalField
        End Get
        Set
            Me.itemTaxTotalField = value
        End Set
    End Property
    
    '''<remarks/>
    Public Property itemType() As String
        Get
            Return Me.itemTypeField
        End Get
        Set
            Me.itemTypeField = value
        End Set
    End Property
    
    '''<remarks/>
    Public Property itemTypeValue() As String
        Get
            Return Me.itemTypeValueField
        End Get
        Set
            Me.itemTypeValueField = value
        End Set
    End Property
    
    '''<remarks/>
    Public Property itemUPC() As String
        Get
            Return Me.itemUPCField
        End Get
        Set
            Me.itemUPCField = value
        End Set
    End Property
    
    '''<remarks/>
    Public Property itemDescription() As String
        Get
            Return Me.itemDescriptionField
        End Get
        Set
            Me.itemDescriptionField = value
        End Set
    End Property
    
    '''<remarks/>
    Public Property itemCategory() As String
        Get
            Return Me.itemCategoryField
        End Get
        Set
            Me.itemCategoryField = value
        End Set
    End Property
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true),  _
 System.Xml.Serialization.XmlRootAttribute([Namespace]:="", IsNullable:=false)>  _
Partial Public Class InitiateKeyedEntryResult
    
    Private statusField As String
    
    '''<remarks/>
    Public Property Status() As String
        Get
            Return Me.statusField
        End Get
        Set
            Me.statusField = value
        End Set
    End Property
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true),  _
 System.Xml.Serialization.XmlRootAttribute([Namespace]:="", IsNullable:=false)>  _
Partial Public Class TransactionResult
    
    Private statusField As String
    
    Private amountApprovedField As Decimal
    
    Private authorizationCodeField As String
    
    Private cardHolderField As String

    'Private cardholderField As String

    Private accountNumberField As String
    
    Private paymentTypeField As String
    
    Private entryModeField As String
    
    Private errorMessageField As String
    
    Private tokenField As String
    
    Private transactionDateField As String
    
    Private transactionTypeField As String
    
    Private responseTypeField As String
    
    Private validationKeyField As String
    
    Private additionalParametersField As AdditionalParameters
    
    '''<remarks/>
    Public Property Status() As String
        Get
            Return Me.statusField
        End Get
        Set
            Me.statusField = value
        End Set
    End Property
    
    '''<remarks/>
    Public Property AmountApproved() As Decimal
        Get
            Return Me.amountApprovedField
        End Get
        Set
            Me.amountApprovedField = value
        End Set
    End Property
    
    '''<remarks/>
    Public Property AuthorizationCode() As String
        Get
            Return Me.authorizationCodeField
        End Get
        Set
            Me.authorizationCodeField = value
        End Set
    End Property
    
    '''<remarks/>
    Public Overloads Property CardHolder() As String
        Get
            Return Me.cardHolderField
        End Get
        Set
            Me.cardHolderField = value
        End Set
    End Property


    'Public Overloads Property Cardholder() As String
    '    Get
    '       Return Me.cardholderField
    '   End Get
    '   Set
    '       Me.cardholderField = value
    '   End Set
    'End Property

    '''<remarks/>
    Public Property AccountNumber() As String
        Get
            Return Me.accountNumberField
        End Get
        Set
            Me.accountNumberField = value
        End Set
    End Property
    
    '''<remarks/>
    Public Property PaymentType() As String
        Get
            Return Me.paymentTypeField
        End Get
        Set
            Me.paymentTypeField = value
        End Set
    End Property
    
    '''<remarks/>
    Public Property EntryMode() As String
        Get
            Return Me.entryModeField
        End Get
        Set
            Me.entryModeField = value
        End Set
    End Property
    
    '''<remarks/>
    Public Property ErrorMessage() As String
        Get
            Return Me.errorMessageField
        End Get
        Set
            Me.errorMessageField = value
        End Set
    End Property
    
    '''<remarks/>
    Public Property Token() As String
        Get
            Return Me.tokenField
        End Get
        Set
            Me.tokenField = value
        End Set
    End Property
    
    '''<remarks/>
    Public Property TransactionDate() As String
        Get
            Return Me.transactionDateField
        End Get
        Set
            Me.transactionDateField = value
        End Set
    End Property
    
    '''<remarks/>
    Public Property TransactionType() As String
        Get
            Return Me.transactionTypeField
        End Get
        Set
            Me.transactionTypeField = value
        End Set
    End Property
    
    '''<remarks/>
    Public Property ResponseType() As String
        Get
            Return Me.responseTypeField
        End Get
        Set
            Me.responseTypeField = value
        End Set
    End Property
    
    '''<remarks/>
    Public Property ValidationKey() As String
        Get
            Return Me.validationKeyField
        End Get
        Set
            Me.validationKeyField = value
        End Set
    End Property
    
    '''<remarks/>
    Public Property AdditionalParameters() As AdditionalParameters
        Get
            Return Me.additionalParametersField
        End Get
        Set
            Me.additionalParametersField = value
        End Set
    End Property
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true),  _
 System.Xml.Serialization.XmlRootAttribute([Namespace]:="", IsNullable:=false)>  _
Partial Public Class AgreementTextResponse
    
    Private requestIDField As String
    
    Private statusField As String
    
    '''<remarks/>
    Public Property RequestID() As String
        Get
            Return Me.requestIDField
        End Get
        Set
            Me.requestIDField = value
        End Set
    End Property
    
    '''<remarks/>
    Public Property Status() As String
        Get
            Return Me.statusField
        End Get
        Set
            Me.statusField = value
        End Set
    End Property
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true),  _
 System.Xml.Serialization.XmlRootAttribute([Namespace]:="", IsNullable:=false)>  _
Partial Public Class GetSignatureResult
    
    Private statusField As String
    
    Private signatureDataField As String
    
    Private requestIDField As String
    
    '''<remarks/>
    Public Property Status() As String
        Get
            Return Me.statusField
        End Get
        Set
            Me.statusField = value
        End Set
    End Property
    
    '''<remarks/>
    Public Property SignatureData() As String
        Get
            Return Me.signatureDataField
        End Get
        Set
            Me.signatureDataField = value
        End Set
    End Property
    
    '''<remarks/>
    Public Property RequestID() As String
        Get
            Return Me.requestIDField
        End Get
        Set
            Me.requestIDField = value
        End Set
    End Property
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true),  _
 System.Xml.Serialization.XmlRootAttribute([Namespace]:="", IsNullable:=false)>  _
Partial Public Class GetCustomerInputResponse
    
    Private statusField As String
    
    Private requestIDField As String
    
    Private valuesField() As GetCustomerInputResponseValue
    
    '''<remarks/>
    Public Property Status() As String
        Get
            Return Me.statusField
        End Get
        Set
            Me.statusField = value
        End Set
    End Property
    
    '''<remarks/>
    Public Property RequestID() As String
        Get
            Return Me.requestIDField
        End Get
        Set
            Me.requestIDField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlArrayItemAttribute("Value", IsNullable:=false)>  _
    Public Property Values() As GetCustomerInputResponseValue()
        Get
            Return Me.valuesField
        End Get
        Set
            Me.valuesField = value
        End Set
    End Property
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true)>  _
Partial Public Class GetCustomerInputResponseValue
    
    Private inputTypeField As String
    
    Private nameField As String
    
    Private valueField As String
    
    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute()>  _
    Public Property inputType() As String
        Get
            Return Me.inputTypeField
        End Get
        Set
            Me.inputTypeField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute()>  _
    Public Property name() As String
        Get
            Return Me.nameField
        End Get
        Set
            Me.nameField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlTextAttribute()>  _
    Public Property Value() As String
        Get
            Return Me.valueField
        End Get
        Set
            Me.valueField = value
        End Set
    End Property
End Class
