'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System
Imports System.Runtime.Serialization

Namespace TransportService
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="TransportRequest", [Namespace]:="http://transport.merchantware.net/v4/"),  _
     System.SerializableAttribute()>  _
    Partial Public Class TransportRequest
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private TransactionTypeField As String
        
        Private AmountField As Decimal
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ClerkIdField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private OrderNumberField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private DbaField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private SoftwareNameField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private SoftwareVersionField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private AddressLine1Field As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ZipField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private CardholderField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private LogoLocationField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private RedirectLocationField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private TransactionIdField As String
        
        Private ForceDuplicateField As Boolean
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private CustomerCodeField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private PoNumberField As String
        
        Private TaxAmountField As Decimal
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private DisplayColorsField As TransportService.DisplayColors
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private DisplayOptionsField As TransportService.DisplayOptions
        
        Private EntryModeField As TransportService.EntryMode
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private AuthorizationCodeField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private TerminalIdField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private HealthCareAmountDetailsField As TransportService.HealthCareAmountDetails
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private EnablePartialAuthorizationField As System.Nullable(Of Boolean)
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private LoyaltyAmountDetailsField As TransportService.LoyaltyAmountDetails
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private TipDetailsField As TransportService.TipDetails
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private InvoiceField As TransportService.Invoice
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false)>  _
        Public Property TransactionType() As String
            Get
                Return Me.TransactionTypeField
            End Get
            Set
                If (Object.ReferenceEquals(Me.TransactionTypeField, value) <> true) Then
                    Me.TransactionTypeField = value
                    Me.RaisePropertyChanged("TransactionType")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true, Order:=1)>  _
        Public Property Amount() As Decimal
            Get
                Return Me.AmountField
            End Get
            Set
                If (Me.AmountField.Equals(value) <> true) Then
                    Me.AmountField = value
                    Me.RaisePropertyChanged("Amount")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=2)>  _
        Public Property ClerkId() As String
            Get
                Return Me.ClerkIdField
            End Get
            Set
                If (Object.ReferenceEquals(Me.ClerkIdField, value) <> true) Then
                    Me.ClerkIdField = value
                    Me.RaisePropertyChanged("ClerkId")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=3)>  _
        Public Property OrderNumber() As String
            Get
                Return Me.OrderNumberField
            End Get
            Set
                If (Object.ReferenceEquals(Me.OrderNumberField, value) <> true) Then
                    Me.OrderNumberField = value
                    Me.RaisePropertyChanged("OrderNumber")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=4)>  _
        Public Property Dba() As String
            Get
                Return Me.DbaField
            End Get
            Set
                If (Object.ReferenceEquals(Me.DbaField, value) <> true) Then
                    Me.DbaField = value
                    Me.RaisePropertyChanged("Dba")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=5)>  _
        Public Property SoftwareName() As String
            Get
                Return Me.SoftwareNameField
            End Get
            Set
                If (Object.ReferenceEquals(Me.SoftwareNameField, value) <> true) Then
                    Me.SoftwareNameField = value
                    Me.RaisePropertyChanged("SoftwareName")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=6)>  _
        Public Property SoftwareVersion() As String
            Get
                Return Me.SoftwareVersionField
            End Get
            Set
                If (Object.ReferenceEquals(Me.SoftwareVersionField, value) <> true) Then
                    Me.SoftwareVersionField = value
                    Me.RaisePropertyChanged("SoftwareVersion")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=7)>  _
        Public Property AddressLine1() As String
            Get
                Return Me.AddressLine1Field
            End Get
            Set
                If (Object.ReferenceEquals(Me.AddressLine1Field, value) <> true) Then
                    Me.AddressLine1Field = value
                    Me.RaisePropertyChanged("AddressLine1")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=8)>  _
        Public Property Zip() As String
            Get
                Return Me.ZipField
            End Get
            Set
                If (Object.ReferenceEquals(Me.ZipField, value) <> true) Then
                    Me.ZipField = value
                    Me.RaisePropertyChanged("Zip")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=9)>  _
        Public Property Cardholder() As String
            Get
                Return Me.CardholderField
            End Get
            Set
                If (Object.ReferenceEquals(Me.CardholderField, value) <> true) Then
                    Me.CardholderField = value
                    Me.RaisePropertyChanged("Cardholder")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=10)>  _
        Public Property LogoLocation() As String
            Get
                Return Me.LogoLocationField
            End Get
            Set
                If (Object.ReferenceEquals(Me.LogoLocationField, value) <> true) Then
                    Me.LogoLocationField = value
                    Me.RaisePropertyChanged("LogoLocation")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=11)>  _
        Public Property RedirectLocation() As String
            Get
                Return Me.RedirectLocationField
            End Get
            Set
                If (Object.ReferenceEquals(Me.RedirectLocationField, value) <> true) Then
                    Me.RedirectLocationField = value
                    Me.RaisePropertyChanged("RedirectLocation")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=12)>  _
        Public Property TransactionId() As String
            Get
                Return Me.TransactionIdField
            End Get
            Set
                If (Object.ReferenceEquals(Me.TransactionIdField, value) <> true) Then
                    Me.TransactionIdField = value
                    Me.RaisePropertyChanged("TransactionId")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true, Order:=13)>  _
        Public Property ForceDuplicate() As Boolean
            Get
                Return Me.ForceDuplicateField
            End Get
            Set
                If (Me.ForceDuplicateField.Equals(value) <> true) Then
                    Me.ForceDuplicateField = value
                    Me.RaisePropertyChanged("ForceDuplicate")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=14)>  _
        Public Property CustomerCode() As String
            Get
                Return Me.CustomerCodeField
            End Get
            Set
                If (Object.ReferenceEquals(Me.CustomerCodeField, value) <> true) Then
                    Me.CustomerCodeField = value
                    Me.RaisePropertyChanged("CustomerCode")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=15)>  _
        Public Property PoNumber() As String
            Get
                Return Me.PoNumberField
            End Get
            Set
                If (Object.ReferenceEquals(Me.PoNumberField, value) <> true) Then
                    Me.PoNumberField = value
                    Me.RaisePropertyChanged("PoNumber")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true, Order:=16)>  _
        Public Property TaxAmount() As Decimal
            Get
                Return Me.TaxAmountField
            End Get
            Set
                If (Me.TaxAmountField.Equals(value) <> true) Then
                    Me.TaxAmountField = value
                    Me.RaisePropertyChanged("TaxAmount")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=17)>  _
        Public Property DisplayColors() As TransportService.DisplayColors
            Get
                Return Me.DisplayColorsField
            End Get
            Set
                If (Object.ReferenceEquals(Me.DisplayColorsField, value) <> true) Then
                    Me.DisplayColorsField = value
                    Me.RaisePropertyChanged("DisplayColors")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=18)>  _
        Public Property DisplayOptions() As TransportService.DisplayOptions
            Get
                Return Me.DisplayOptionsField
            End Get
            Set
                If (Object.ReferenceEquals(Me.DisplayOptionsField, value) <> true) Then
                    Me.DisplayOptionsField = value
                    Me.RaisePropertyChanged("DisplayOptions")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true, Order:=19)>  _
        Public Property EntryMode() As TransportService.EntryMode
            Get
                Return Me.EntryModeField
            End Get
            Set
                If (Me.EntryModeField.Equals(value) <> true) Then
                    Me.EntryModeField = value
                    Me.RaisePropertyChanged("EntryMode")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=20)>  _
        Public Property AuthorizationCode() As String
            Get
                Return Me.AuthorizationCodeField
            End Get
            Set
                If (Object.ReferenceEquals(Me.AuthorizationCodeField, value) <> true) Then
                    Me.AuthorizationCodeField = value
                    Me.RaisePropertyChanged("AuthorizationCode")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=21)>  _
        Public Property TerminalId() As String
            Get
                Return Me.TerminalIdField
            End Get
            Set
                If (Object.ReferenceEquals(Me.TerminalIdField, value) <> true) Then
                    Me.TerminalIdField = value
                    Me.RaisePropertyChanged("TerminalId")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=22)>  _
        Public Property HealthCareAmountDetails() As TransportService.HealthCareAmountDetails
            Get
                Return Me.HealthCareAmountDetailsField
            End Get
            Set
                If (Object.ReferenceEquals(Me.HealthCareAmountDetailsField, value) <> true) Then
                    Me.HealthCareAmountDetailsField = value
                    Me.RaisePropertyChanged("HealthCareAmountDetails")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=23)>  _
        Public Property EnablePartialAuthorization() As System.Nullable(Of Boolean)
            Get
                Return Me.EnablePartialAuthorizationField
            End Get
            Set
                If (Me.EnablePartialAuthorizationField.Equals(value) <> true) Then
                    Me.EnablePartialAuthorizationField = value
                    Me.RaisePropertyChanged("EnablePartialAuthorization")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=24)>  _
        Public Property LoyaltyAmountDetails() As TransportService.LoyaltyAmountDetails
            Get
                Return Me.LoyaltyAmountDetailsField
            End Get
            Set
                If (Object.ReferenceEquals(Me.LoyaltyAmountDetailsField, value) <> true) Then
                    Me.LoyaltyAmountDetailsField = value
                    Me.RaisePropertyChanged("LoyaltyAmountDetails")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=25)>  _
        Public Property TipDetails() As TransportService.TipDetails
            Get
                Return Me.TipDetailsField
            End Get
            Set
                If (Object.ReferenceEquals(Me.TipDetailsField, value) <> true) Then
                    Me.TipDetailsField = value
                    Me.RaisePropertyChanged("TipDetails")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=26)>  _
        Public Property Invoice() As TransportService.Invoice
            Get
                Return Me.InvoiceField
            End Get
            Set
                If (Object.ReferenceEquals(Me.InvoiceField, value) <> true) Then
                    Me.InvoiceField = value
                    Me.RaisePropertyChanged("Invoice")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="DisplayColors", [Namespace]:="http://transport.merchantware.net/v4/"),  _
     System.SerializableAttribute()>  _
    Partial Public Class DisplayColors
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ScreenBackgroundColorField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ContainerBackgroundColorField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ContainerFontColorField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ContainerHelpFontColorField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ContainerBorderColorField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private LogoBackgroundColorField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private LogoBorderColorField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private TooltipBackgroundColorField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private TooltipBorderColorField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private TooltipFontColorField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private TextboxBackgroundColorField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private TextboxBorderColorField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private TextboxFocusBackgroundColorField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private TextboxFocusBorderColorField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private TextboxFontColorField As String
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false)>  _
        Public Property ScreenBackgroundColor() As String
            Get
                Return Me.ScreenBackgroundColorField
            End Get
            Set
                If (Object.ReferenceEquals(Me.ScreenBackgroundColorField, value) <> true) Then
                    Me.ScreenBackgroundColorField = value
                    Me.RaisePropertyChanged("ScreenBackgroundColor")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=1)>  _
        Public Property ContainerBackgroundColor() As String
            Get
                Return Me.ContainerBackgroundColorField
            End Get
            Set
                If (Object.ReferenceEquals(Me.ContainerBackgroundColorField, value) <> true) Then
                    Me.ContainerBackgroundColorField = value
                    Me.RaisePropertyChanged("ContainerBackgroundColor")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=2)>  _
        Public Property ContainerFontColor() As String
            Get
                Return Me.ContainerFontColorField
            End Get
            Set
                If (Object.ReferenceEquals(Me.ContainerFontColorField, value) <> true) Then
                    Me.ContainerFontColorField = value
                    Me.RaisePropertyChanged("ContainerFontColor")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=3)>  _
        Public Property ContainerHelpFontColor() As String
            Get
                Return Me.ContainerHelpFontColorField
            End Get
            Set
                If (Object.ReferenceEquals(Me.ContainerHelpFontColorField, value) <> true) Then
                    Me.ContainerHelpFontColorField = value
                    Me.RaisePropertyChanged("ContainerHelpFontColor")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=4)>  _
        Public Property ContainerBorderColor() As String
            Get
                Return Me.ContainerBorderColorField
            End Get
            Set
                If (Object.ReferenceEquals(Me.ContainerBorderColorField, value) <> true) Then
                    Me.ContainerBorderColorField = value
                    Me.RaisePropertyChanged("ContainerBorderColor")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=5)>  _
        Public Property LogoBackgroundColor() As String
            Get
                Return Me.LogoBackgroundColorField
            End Get
            Set
                If (Object.ReferenceEquals(Me.LogoBackgroundColorField, value) <> true) Then
                    Me.LogoBackgroundColorField = value
                    Me.RaisePropertyChanged("LogoBackgroundColor")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=6)>  _
        Public Property LogoBorderColor() As String
            Get
                Return Me.LogoBorderColorField
            End Get
            Set
                If (Object.ReferenceEquals(Me.LogoBorderColorField, value) <> true) Then
                    Me.LogoBorderColorField = value
                    Me.RaisePropertyChanged("LogoBorderColor")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=7)>  _
        Public Property TooltipBackgroundColor() As String
            Get
                Return Me.TooltipBackgroundColorField
            End Get
            Set
                If (Object.ReferenceEquals(Me.TooltipBackgroundColorField, value) <> true) Then
                    Me.TooltipBackgroundColorField = value
                    Me.RaisePropertyChanged("TooltipBackgroundColor")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=8)>  _
        Public Property TooltipBorderColor() As String
            Get
                Return Me.TooltipBorderColorField
            End Get
            Set
                If (Object.ReferenceEquals(Me.TooltipBorderColorField, value) <> true) Then
                    Me.TooltipBorderColorField = value
                    Me.RaisePropertyChanged("TooltipBorderColor")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=9)>  _
        Public Property TooltipFontColor() As String
            Get
                Return Me.TooltipFontColorField
            End Get
            Set
                If (Object.ReferenceEquals(Me.TooltipFontColorField, value) <> true) Then
                    Me.TooltipFontColorField = value
                    Me.RaisePropertyChanged("TooltipFontColor")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=10)>  _
        Public Property TextboxBackgroundColor() As String
            Get
                Return Me.TextboxBackgroundColorField
            End Get
            Set
                If (Object.ReferenceEquals(Me.TextboxBackgroundColorField, value) <> true) Then
                    Me.TextboxBackgroundColorField = value
                    Me.RaisePropertyChanged("TextboxBackgroundColor")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=11)>  _
        Public Property TextboxBorderColor() As String
            Get
                Return Me.TextboxBorderColorField
            End Get
            Set
                If (Object.ReferenceEquals(Me.TextboxBorderColorField, value) <> true) Then
                    Me.TextboxBorderColorField = value
                    Me.RaisePropertyChanged("TextboxBorderColor")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=12)>  _
        Public Property TextboxFocusBackgroundColor() As String
            Get
                Return Me.TextboxFocusBackgroundColorField
            End Get
            Set
                If (Object.ReferenceEquals(Me.TextboxFocusBackgroundColorField, value) <> true) Then
                    Me.TextboxFocusBackgroundColorField = value
                    Me.RaisePropertyChanged("TextboxFocusBackgroundColor")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=13)>  _
        Public Property TextboxFocusBorderColor() As String
            Get
                Return Me.TextboxFocusBorderColorField
            End Get
            Set
                If (Object.ReferenceEquals(Me.TextboxFocusBorderColorField, value) <> true) Then
                    Me.TextboxFocusBorderColorField = value
                    Me.RaisePropertyChanged("TextboxFocusBorderColor")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=14)>  _
        Public Property TextboxFontColor() As String
            Get
                Return Me.TextboxFontColorField
            End Get
            Set
                If (Object.ReferenceEquals(Me.TextboxFontColorField, value) <> true) Then
                    Me.TextboxFontColorField = value
                    Me.RaisePropertyChanged("TextboxFontColor")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="DisplayOptions", [Namespace]:="http://transport.merchantware.net/v4/"),  _
     System.SerializableAttribute()>  _
    Partial Public Class DisplayOptions
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        Private AlignLeftField As Boolean
        
        Private NoCardNumberMaskField As Boolean
        
        Private HideDetailsField As Boolean
        
        Private HideDowngradeMessageField As Boolean
        
        Private HideMessageField As Boolean
        
        Private HideTooltipsField As Boolean
        
        Private UseNativeButtonsField As Boolean
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true)>  _
        Public Property AlignLeft() As Boolean
            Get
                Return Me.AlignLeftField
            End Get
            Set
                If (Me.AlignLeftField.Equals(value) <> true) Then
                    Me.AlignLeftField = value
                    Me.RaisePropertyChanged("AlignLeft")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true)>  _
        Public Property NoCardNumberMask() As Boolean
            Get
                Return Me.NoCardNumberMaskField
            End Get
            Set
                If (Me.NoCardNumberMaskField.Equals(value) <> true) Then
                    Me.NoCardNumberMaskField = value
                    Me.RaisePropertyChanged("NoCardNumberMask")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true, Order:=2)>  _
        Public Property HideDetails() As Boolean
            Get
                Return Me.HideDetailsField
            End Get
            Set
                If (Me.HideDetailsField.Equals(value) <> true) Then
                    Me.HideDetailsField = value
                    Me.RaisePropertyChanged("HideDetails")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true, Order:=3)>  _
        Public Property HideDowngradeMessage() As Boolean
            Get
                Return Me.HideDowngradeMessageField
            End Get
            Set
                If (Me.HideDowngradeMessageField.Equals(value) <> true) Then
                    Me.HideDowngradeMessageField = value
                    Me.RaisePropertyChanged("HideDowngradeMessage")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true, Order:=4)>  _
        Public Property HideMessage() As Boolean
            Get
                Return Me.HideMessageField
            End Get
            Set
                If (Me.HideMessageField.Equals(value) <> true) Then
                    Me.HideMessageField = value
                    Me.RaisePropertyChanged("HideMessage")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true, Order:=5)>  _
        Public Property HideTooltips() As Boolean
            Get
                Return Me.HideTooltipsField
            End Get
            Set
                If (Me.HideTooltipsField.Equals(value) <> true) Then
                    Me.HideTooltipsField = value
                    Me.RaisePropertyChanged("HideTooltips")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true, Order:=6)>  _
        Public Property UseNativeButtons() As Boolean
            Get
                Return Me.UseNativeButtonsField
            End Get
            Set
                If (Me.UseNativeButtonsField.Equals(value) <> true) Then
                    Me.UseNativeButtonsField = value
                    Me.RaisePropertyChanged("UseNativeButtons")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="HealthCareAmountDetails", [Namespace]:="http://transport.merchantware.net/v4/"),  _
     System.SerializableAttribute()>  _
    Partial Public Class HealthCareAmountDetails
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        Private CopayAmountField As Decimal
        
        Private ClinicalAmountField As Decimal
        
        Private DentalAmountField As Decimal
        
        Private HealthCareTotalAmountField As Decimal
        
        Private PrescriptionAmountField As Decimal
        
        Private VisionAmountField As Decimal
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true)>  _
        Public Property CopayAmount() As Decimal
            Get
                Return Me.CopayAmountField
            End Get
            Set
                If (Me.CopayAmountField.Equals(value) <> true) Then
                    Me.CopayAmountField = value
                    Me.RaisePropertyChanged("CopayAmount")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true, Order:=1)>  _
        Public Property ClinicalAmount() As Decimal
            Get
                Return Me.ClinicalAmountField
            End Get
            Set
                If (Me.ClinicalAmountField.Equals(value) <> true) Then
                    Me.ClinicalAmountField = value
                    Me.RaisePropertyChanged("ClinicalAmount")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true, Order:=2)>  _
        Public Property DentalAmount() As Decimal
            Get
                Return Me.DentalAmountField
            End Get
            Set
                If (Me.DentalAmountField.Equals(value) <> true) Then
                    Me.DentalAmountField = value
                    Me.RaisePropertyChanged("DentalAmount")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true, Order:=3)>  _
        Public Property HealthCareTotalAmount() As Decimal
            Get
                Return Me.HealthCareTotalAmountField
            End Get
            Set
                If (Me.HealthCareTotalAmountField.Equals(value) <> true) Then
                    Me.HealthCareTotalAmountField = value
                    Me.RaisePropertyChanged("HealthCareTotalAmount")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true, Order:=4)>  _
        Public Property PrescriptionAmount() As Decimal
            Get
                Return Me.PrescriptionAmountField
            End Get
            Set
                If (Me.PrescriptionAmountField.Equals(value) <> true) Then
                    Me.PrescriptionAmountField = value
                    Me.RaisePropertyChanged("PrescriptionAmount")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true, Order:=5)>  _
        Public Property VisionAmount() As Decimal
            Get
                Return Me.VisionAmountField
            End Get
            Set
                If (Me.VisionAmountField.Equals(value) <> true) Then
                    Me.VisionAmountField = value
                    Me.RaisePropertyChanged("VisionAmount")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="LoyaltyAmountDetails", [Namespace]:="http://transport.merchantware.net/v4/"),  _
     System.SerializableAttribute()>  _
    Partial Public Class LoyaltyAmountDetails
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        Private EligibleAmountField As Decimal
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true)>  _
        Public Property EligibleAmount() As Decimal
            Get
                Return Me.EligibleAmountField
            End Get
            Set
                If (Me.EligibleAmountField.Equals(value) <> true) Then
                    Me.EligibleAmountField = value
                    Me.RaisePropertyChanged("EligibleAmount")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="TipDetails", [Namespace]:="http://transport.merchantware.net/v4/"),  _
     System.SerializableAttribute()>  _
    Partial Public Class TipDetails
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private EligibleAmountField As Decimal
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property EligibleAmount() As Decimal
            Get
                Return Me.EligibleAmountField
            End Get
            Set
                If (Me.EligibleAmountField.Equals(value) <> true) Then
                    Me.EligibleAmountField = value
                    Me.RaisePropertyChanged("EligibleAmount")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="Invoice", [Namespace]:="http://transport.merchantware.net/v4/"),  _
     System.SerializableAttribute()>  _
    Partial Public Class Invoice
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private TaxIndicatorField As TransportService.TaxIndicator
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ProductDescriptionField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private DiscountAmountField As System.Nullable(Of Decimal)
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ShippingAmountField As System.Nullable(Of Decimal)
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private DutyAmountField As System.Nullable(Of Decimal)
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private DestinationPostalCodeField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private DestinationCountryCodeField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ShipFromPostalCodeField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private AlternateTaxAmountField As System.Nullable(Of Decimal)
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private AlternateTaxRateField As System.Nullable(Of Decimal)
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private LineItemsField() As TransportService.LineItem
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property TaxIndicator() As TransportService.TaxIndicator
            Get
                Return Me.TaxIndicatorField
            End Get
            Set
                If (Me.TaxIndicatorField.Equals(value) <> true) Then
                    Me.TaxIndicatorField = value
                    Me.RaisePropertyChanged("TaxIndicator")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=1)>  _
        Public Property ProductDescription() As String
            Get
                Return Me.ProductDescriptionField
            End Get
            Set
                If (Object.ReferenceEquals(Me.ProductDescriptionField, value) <> true) Then
                    Me.ProductDescriptionField = value
                    Me.RaisePropertyChanged("ProductDescription")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=2)>  _
        Public Property DiscountAmount() As System.Nullable(Of Decimal)
            Get
                Return Me.DiscountAmountField
            End Get
            Set
                If (Me.DiscountAmountField.Equals(value) <> true) Then
                    Me.DiscountAmountField = value
                    Me.RaisePropertyChanged("DiscountAmount")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=3)>  _
        Public Property ShippingAmount() As System.Nullable(Of Decimal)
            Get
                Return Me.ShippingAmountField
            End Get
            Set
                If (Me.ShippingAmountField.Equals(value) <> true) Then
                    Me.ShippingAmountField = value
                    Me.RaisePropertyChanged("ShippingAmount")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=4)>  _
        Public Property DutyAmount() As System.Nullable(Of Decimal)
            Get
                Return Me.DutyAmountField
            End Get
            Set
                If (Me.DutyAmountField.Equals(value) <> true) Then
                    Me.DutyAmountField = value
                    Me.RaisePropertyChanged("DutyAmount")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=5)>  _
        Public Property DestinationPostalCode() As String
            Get
                Return Me.DestinationPostalCodeField
            End Get
            Set
                If (Object.ReferenceEquals(Me.DestinationPostalCodeField, value) <> true) Then
                    Me.DestinationPostalCodeField = value
                    Me.RaisePropertyChanged("DestinationPostalCode")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=6)>  _
        Public Property DestinationCountryCode() As String
            Get
                Return Me.DestinationCountryCodeField
            End Get
            Set
                If (Object.ReferenceEquals(Me.DestinationCountryCodeField, value) <> true) Then
                    Me.DestinationCountryCodeField = value
                    Me.RaisePropertyChanged("DestinationCountryCode")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=7)>  _
        Public Property ShipFromPostalCode() As String
            Get
                Return Me.ShipFromPostalCodeField
            End Get
            Set
                If (Object.ReferenceEquals(Me.ShipFromPostalCodeField, value) <> true) Then
                    Me.ShipFromPostalCodeField = value
                    Me.RaisePropertyChanged("ShipFromPostalCode")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=8)>  _
        Public Property AlternateTaxAmount() As System.Nullable(Of Decimal)
            Get
                Return Me.AlternateTaxAmountField
            End Get
            Set
                If (Me.AlternateTaxAmountField.Equals(value) <> true) Then
                    Me.AlternateTaxAmountField = value
                    Me.RaisePropertyChanged("AlternateTaxAmount")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=9)>  _
        Public Property AlternateTaxRate() As System.Nullable(Of Decimal)
            Get
                Return Me.AlternateTaxRateField
            End Get
            Set
                If (Me.AlternateTaxRateField.Equals(value) <> true) Then
                    Me.AlternateTaxRateField = value
                    Me.RaisePropertyChanged("AlternateTaxRate")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=10)>  _
        Public Property LineItems() As TransportService.LineItem()
            Get
                Return Me.LineItemsField
            End Get
            Set
                If (Object.ReferenceEquals(Me.LineItemsField, value) <> true) Then
                    Me.LineItemsField = value
                    Me.RaisePropertyChanged("LineItems")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="EntryMode", [Namespace]:="http://transport.merchantware.net/v4/")>  _
    Public Enum EntryMode As Integer
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        Undefined = 0
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        Keyed = 1
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        Swiped = 2
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        KeyedSwiped = 3
    End Enum
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="TaxIndicator", [Namespace]:="http://transport.merchantware.net/v4/")>  _
    Public Enum TaxIndicator As Integer
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        Unspecified = 0
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        NotProvided = 1
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        Provided = 2
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        Exempt = 3
    End Enum
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="LineItem", [Namespace]:="http://transport.merchantware.net/v4/"),  _
     System.SerializableAttribute()>  _
    Partial Public Class LineItem
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private CommodityCodeField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private DescriptionField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private UpcField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private QuantityField As System.Nullable(Of Decimal)
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private UnitOfMeasureField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private UnitCostField As System.Nullable(Of Decimal)
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private DiscountAmountField As System.Nullable(Of Decimal)
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private TotalAmountField As System.Nullable(Of Decimal)
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private TaxAmountField As System.Nullable(Of Decimal)
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ExtendedAmountField As System.Nullable(Of Decimal)
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private DebitOrCreditIndicatorField As TransportService.DebitOrCreditIndicator
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private NetOrGrossIndicatorField As TransportService.NetOrGrossIndicator
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false)>  _
        Public Property CommodityCode() As String
            Get
                Return Me.CommodityCodeField
            End Get
            Set
                If (Object.ReferenceEquals(Me.CommodityCodeField, value) <> true) Then
                    Me.CommodityCodeField = value
                    Me.RaisePropertyChanged("CommodityCode")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false)>  _
        Public Property Description() As String
            Get
                Return Me.DescriptionField
            End Get
            Set
                If (Object.ReferenceEquals(Me.DescriptionField, value) <> true) Then
                    Me.DescriptionField = value
                    Me.RaisePropertyChanged("Description")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false)>  _
        Public Property Upc() As String
            Get
                Return Me.UpcField
            End Get
            Set
                If (Object.ReferenceEquals(Me.UpcField, value) <> true) Then
                    Me.UpcField = value
                    Me.RaisePropertyChanged("Upc")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=3)>  _
        Public Property Quantity() As System.Nullable(Of Decimal)
            Get
                Return Me.QuantityField
            End Get
            Set
                If (Me.QuantityField.Equals(value) <> true) Then
                    Me.QuantityField = value
                    Me.RaisePropertyChanged("Quantity")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=4)>  _
        Public Property UnitOfMeasure() As String
            Get
                Return Me.UnitOfMeasureField
            End Get
            Set
                If (Object.ReferenceEquals(Me.UnitOfMeasureField, value) <> true) Then
                    Me.UnitOfMeasureField = value
                    Me.RaisePropertyChanged("UnitOfMeasure")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=5)>  _
        Public Property UnitCost() As System.Nullable(Of Decimal)
            Get
                Return Me.UnitCostField
            End Get
            Set
                If (Me.UnitCostField.Equals(value) <> true) Then
                    Me.UnitCostField = value
                    Me.RaisePropertyChanged("UnitCost")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=6)>  _
        Public Property DiscountAmount() As System.Nullable(Of Decimal)
            Get
                Return Me.DiscountAmountField
            End Get
            Set
                If (Me.DiscountAmountField.Equals(value) <> true) Then
                    Me.DiscountAmountField = value
                    Me.RaisePropertyChanged("DiscountAmount")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=7)>  _
        Public Property TotalAmount() As System.Nullable(Of Decimal)
            Get
                Return Me.TotalAmountField
            End Get
            Set
                If (Me.TotalAmountField.Equals(value) <> true) Then
                    Me.TotalAmountField = value
                    Me.RaisePropertyChanged("TotalAmount")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=8)>  _
        Public Property TaxAmount() As System.Nullable(Of Decimal)
            Get
                Return Me.TaxAmountField
            End Get
            Set
                If (Me.TaxAmountField.Equals(value) <> true) Then
                    Me.TaxAmountField = value
                    Me.RaisePropertyChanged("TaxAmount")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=9)>  _
        Public Property ExtendedAmount() As System.Nullable(Of Decimal)
            Get
                Return Me.ExtendedAmountField
            End Get
            Set
                If (Me.ExtendedAmountField.Equals(value) <> true) Then
                    Me.ExtendedAmountField = value
                    Me.RaisePropertyChanged("ExtendedAmount")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=10)>  _
        Public Property DebitOrCreditIndicator() As TransportService.DebitOrCreditIndicator
            Get
                Return Me.DebitOrCreditIndicatorField
            End Get
            Set
                If (Me.DebitOrCreditIndicatorField.Equals(value) <> true) Then
                    Me.DebitOrCreditIndicatorField = value
                    Me.RaisePropertyChanged("DebitOrCreditIndicator")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=11)>  _
        Public Property NetOrGrossIndicator() As TransportService.NetOrGrossIndicator
            Get
                Return Me.NetOrGrossIndicatorField
            End Get
            Set
                If (Me.NetOrGrossIndicatorField.Equals(value) <> true) Then
                    Me.NetOrGrossIndicatorField = value
                    Me.RaisePropertyChanged("NetOrGrossIndicator")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="DebitOrCreditIndicator", [Namespace]:="http://transport.merchantware.net/v4/")>  _
    Public Enum DebitOrCreditIndicator As Integer
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        Unspecified = 0
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        Credit = 1
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        Debit = 2
    End Enum
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="NetOrGrossIndicator", [Namespace]:="http://transport.merchantware.net/v4/")>  _
    Public Enum NetOrGrossIndicator As Integer
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        Unspecified = 0
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        Net = 1
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        Gross = 2
    End Enum
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="TransportResponse", [Namespace]:="http://transport.merchantware.net/v4/"),  _
     System.SerializableAttribute()>  _
    Partial Public Class TransportResponse
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private TransportKeyField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ValidationKeyField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private MessagesField() As TransportService.Message
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false)>  _
        Public Property TransportKey() As String
            Get
                Return Me.TransportKeyField
            End Get
            Set
                If (Object.ReferenceEquals(Me.TransportKeyField, value) <> true) Then
                    Me.TransportKeyField = value
                    Me.RaisePropertyChanged("TransportKey")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false)>  _
        Public Property ValidationKey() As String
            Get
                Return Me.ValidationKeyField
            End Get
            Set
                If (Object.ReferenceEquals(Me.ValidationKeyField, value) <> true) Then
                    Me.ValidationKeyField = value
                    Me.RaisePropertyChanged("ValidationKey")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=2)>  _
        Public Property Messages() As TransportService.Message()
            Get
                Return Me.MessagesField
            End Get
            Set
                If (Object.ReferenceEquals(Me.MessagesField, value) <> true) Then
                    Me.MessagesField = value
                    Me.RaisePropertyChanged("Messages")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="Message", [Namespace]:="http://transport.merchantware.net/v4/"),  _
     System.SerializableAttribute()>  _
    Partial Public Class Message
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private FieldField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private InformationField As String
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false)>  _
        Public Property Field() As String
            Get
                Return Me.FieldField
            End Get
            Set
                If (Object.ReferenceEquals(Me.FieldField, value) <> true) Then
                    Me.FieldField = value
                    Me.RaisePropertyChanged("Field")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false)>  _
        Public Property Information() As String
            Get
                Return Me.InformationField
            End Get
            Set
                If (Object.ReferenceEquals(Me.InformationField, value) <> true) Then
                    Me.InformationField = value
                    Me.RaisePropertyChanged("Information")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute([Namespace]:="http://transport.merchantware.net/v4/", ConfigurationName:="TransportService.TransportServiceSoap")>  _
    Public Interface TransportServiceSoap
        
        'CODEGEN: Generating message contract since element name merchantName from namespace http://transport.merchantware.net/v4/ is not marked nillable
        <System.ServiceModel.OperationContractAttribute(Action:="http://transport.merchantware.net/v4/CreateTransaction", ReplyAction:="*")>  _
        Function CreateTransaction(ByVal request As TransportService.CreateTransactionRequest) As TransportService.CreateTransactionResponse
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://transport.merchantware.net/v4/CreateTransaction", ReplyAction:="*")>  _
        Function CreateTransactionAsync(ByVal request As TransportService.CreateTransactionRequest) As System.Threading.Tasks.Task(Of TransportService.CreateTransactionResponse)
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class CreateTransactionRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="CreateTransaction", [Namespace]:="http://transport.merchantware.net/v4/", Order:=0)>  _
        Public Body As TransportService.CreateTransactionRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As TransportService.CreateTransactionRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://transport.merchantware.net/v4/")>  _
    Partial Public Class CreateTransactionRequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public merchantName As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=1)>  _
        Public merchantSiteId As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=2)>  _
        Public merchantKey As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=3)>  _
        Public request As TransportService.TransportRequest
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal merchantName As String, ByVal merchantSiteId As String, ByVal merchantKey As String, ByVal request As TransportService.TransportRequest)
            MyBase.New
            Me.merchantName = merchantName
            Me.merchantSiteId = merchantSiteId
            Me.merchantKey = merchantKey
            Me.request = request
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class CreateTransactionResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="CreateTransactionResponse", [Namespace]:="http://transport.merchantware.net/v4/", Order:=0)>  _
        Public Body As TransportService.CreateTransactionResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As TransportService.CreateTransactionResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://transport.merchantware.net/v4/")>  _
    Partial Public Class CreateTransactionResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public CreateTransactionResult As TransportService.TransportResponse
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal CreateTransactionResult As TransportService.TransportResponse)
            MyBase.New
            Me.CreateTransactionResult = CreateTransactionResult
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface TransportServiceSoapChannel
        Inherits TransportService.TransportServiceSoap, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class TransportServiceSoapClient
        Inherits System.ServiceModel.ClientBase(Of TransportService.TransportServiceSoap)
        Implements TransportService.TransportServiceSoap
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function TransportService_TransportServiceSoap_CreateTransaction(ByVal request As TransportService.CreateTransactionRequest) As TransportService.CreateTransactionResponse Implements TransportService.TransportServiceSoap.CreateTransaction
            Return MyBase.Channel.CreateTransaction(request)
        End Function
        
        Public Function CreateTransaction(ByVal merchantName As String, ByVal merchantSiteId As String, ByVal merchantKey As String, ByVal request As TransportService.TransportRequest) As TransportService.TransportResponse
            Dim inValue As TransportService.CreateTransactionRequest = New TransportService.CreateTransactionRequest()
            inValue.Body = New TransportService.CreateTransactionRequestBody()
            inValue.Body.merchantName = merchantName
            inValue.Body.merchantSiteId = merchantSiteId
            inValue.Body.merchantKey = merchantKey
            inValue.Body.request = request
            Dim retVal As TransportService.CreateTransactionResponse = CType(Me,TransportService.TransportServiceSoap).CreateTransaction(inValue)
            Return retVal.Body.CreateTransactionResult
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function TransportService_TransportServiceSoap_CreateTransactionAsync(ByVal request As TransportService.CreateTransactionRequest) As System.Threading.Tasks.Task(Of TransportService.CreateTransactionResponse) Implements TransportService.TransportServiceSoap.CreateTransactionAsync
            Return MyBase.Channel.CreateTransactionAsync(request)
        End Function
        
        Public Function CreateTransactionAsync(ByVal merchantName As String, ByVal merchantSiteId As String, ByVal merchantKey As String, ByVal request As TransportService.TransportRequest) As System.Threading.Tasks.Task(Of TransportService.CreateTransactionResponse)
            Dim inValue As TransportService.CreateTransactionRequest = New TransportService.CreateTransactionRequest()
            inValue.Body = New TransportService.CreateTransactionRequestBody()
            inValue.Body.merchantName = merchantName
            inValue.Body.merchantSiteId = merchantSiteId
            inValue.Body.merchantKey = merchantKey
            inValue.Body.request = request
            Return CType(Me,TransportService.TransportServiceSoap).CreateTransactionAsync(inValue)
        End Function
    End Class
End Namespace
